name: Docker build core, devel, latest [later will build service-devel and service]

on:
  pull_request:
    branches: [ master ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install docker and pre-reqs
        shell: bash -l {0}
        run: |
         # make the file runnable
         chmod +x ".github/workflows/install_docker.sh"
         .github/workflows/install_docker.sh
         
      - name: Build docker core image
        # Builds docker image from Docker file.
        shell: bash -l {0}
        run: |
          docker-compose -f docker/docker-compose.yml pull core # is this needed here - does it do anything?
          docker-compose -f docker/docker-compose.yml build --pull core 
          
      - name : docker save core
        # https://docs.docker.com/engine/reference/commandline/save/
        shell: bash -l {0}
        run: |
          docker save -o core.tar synerbi/sirf:core
          
      - name: Upload artifact of the core image.
        uses: actions/upload-artifact@v2
        with:
          name: sirf-core
          path: core.tar
          
          
  build-core-gpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install docker and pre-reqs
        shell: bash -l {0}
        run: |
         # make the file runnable
         chmod +x ".github/workflows/install_docker.sh"
         .github/workflows/install_docker.sh
          
      - name: Build docker core-gpu image
        # Builds docker image from Docker file.
        shell: bash -l {0}
        run: |
          docker-compose -f docker/docker-compose.yml build --pull core 
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.srv-gpu.yml build core
          
      - name : docker save core-gpu
        # https://docs.docker.com/engine/reference/commandline/save/
        shell: bash -l {0}
        run: |
          docker save -o core-gpu.tar synerbi/sirf:core-gpu
          
      - name: Upload artifact of the core image.
        uses: actions/upload-artifact@v2
        with:
          name: sirf-core-gpu
          path: core-gpu.tar
      
  build-devel-and-latest:
    runs-on: ubuntu-latest
    needs: build-core
    strategy:
      matrix:
        tag: ['latest', 'devel']
    steps:
      - name: Install docker and pre-reqs
        shell: bash -l {0}
        run: |
         # make the file runnable
         chmod +x ".github/workflows/install_docker.sh"
         .github/workflows/install_docker.sh
          
      - name: Download artifact of core image
        uses: actions/download-artifact@v2
        with:
          name: sirf-core
          path: /tmp

      - name: load core
        shell: bash -l {0}
        run: |
          docker load --input /tmp/core.tar
      
      - name: Build docker image
        # Builds docker image from Docker file.
        shell: bash -l {0}
        run: |
          export compose_command="docker-compose -f docker/docker-compose.yml"
          if [[${{ matrix.tag }} == 'devel']]; then export compose_command="$compose_command + -f docker/docker-compose.devel.yml"; fi
          $compose_command pull core
          $compose_command build --pull sirf

      - name: Run docker service container with tests
        shell: bash -l {0}
        run: |
          compose_command run --rm -u jovyan --entrypoint /bin/bash sirf --login -c /devel/test.sh 1
          
      - name : docker save image
        # https://docs.docker.com/engine/reference/commandline/save/
        shell: bash -l {0}
        run: |
          docker save -o ${{ matrix.tag }}.tar synerbi/sirf:${{ matrix.tag }}
          
      - name: Upload artifact of image.
        uses: actions/upload-artifact@v2
        with:
          name: sirf-${{ matrix.tag }}
          path: ${{ matrix.tag }}.tar
          
  build-service-gpu:
      runs-on: ubuntu-latest
      needs: build-core-gpu
      steps:
        - uses: actions/checkout@v3
        - name: Install docker and pre-reqs
          shell: bash -l {0}
          run: |
           # make the file runnable
           chmod +x ".github/workflows/install_docker.sh"
           .github/workflows/install_docker.sh

        - name: Download artifact of core image
          uses: actions/download-artifact@v2
          with:
            name: sirf-core-gpu
            path: /tmp

        - name: load core-gpu
          shell: bash -l {0}
          run: |
            docker load --input /tmp/core-gpu.tar

        - name: Build docker service-gpu image
          # Builds docker image from Docker file.
          shell: bash -l {0}
          run: |
            docker-compose -f docker/docker-compose.yml -f docker/docker-compose.srv-gpu.yml build --pull core 
            docker-compose -f docker/docker-compose.yml -f docker/docker-compose.srv-gpu.yml build sirf
            
  build-service-images:
    runs-on: ubuntu-latest
    needs: build-devel-and-latest
    strategy:
      matrix:
        tag: ['service', 'service-devel']
    steps:
      - name: Install docker and pre-reqs
        shell: bash -l {0}
        run: |
         # make the file runnable
         chmod +x ".github/workflows/install_docker.sh"
         .github/workflows/install_docker.sh
         
      - name: setup variables
        shell: bash -l {0}
        run: |
          export compose_command="docker-compose -f docker/docker-compose.yml"
           
          if [[${{ matrix.tag }} == 'service']]; 
          then
            export prereq_image_name="latest"
            export compose_command="$compose_command + -f docker/docker-compose.srv.yml"
          fi
          if [[${{ matrix.tag }} == 'service-devel']]
          then
            export prereq_image_name="devel"
            export compose_command="$compose_command + -f docker/docker-compose.devel.yml + -f docker/docker-compose.srv.yml"
          fi
          if [[${{ matrix.tag }} == 'devel']]; then ; fi
          
          
      - name: Download artifact of image
        uses: actions/download-artifact@v2
        with:
          name: sirf-$prereq_image_name
          path: /tmp

      - name: load core
        shell: bash -l {0}
        run: |
          docker load --input /tmp/$prereq_image_name.tar
      
      - name: Build docker image
        # Builds docker image from Docker file.
        shell: bash -l {0}
        run: |
          $compose_command pull $prereq_image_name
          $compose_command build --pull sirf

      - name: Run docker service container with tests
        shell: bash -l {0}
        run: |
          compose_command run --rm -u jovyan --entrypoint /bin/bash sirf --login -c /devel/test.sh 1
          
      - name : docker save image
        # https://docs.docker.com/engine/reference/commandline/save/
        shell: bash -l {0}
        run: |
          docker save -o ${{ matrix.tag }}.tar synerbi/sirf:${{ matrix.tag }}
          
      - name: Upload artifact of image.
        uses: actions/upload-artifact@v2
        with:
          name: sirf-${{ matrix.tag }}
          path: ${{ matrix.tag }}.tar
      
#       - name: Build docker devel image
#         # Builds docker image from Docker file.
#         shell: bash -l {0}
#         run: |
#           docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml pull core
#           docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml build sirf

#       - name: Run docker devel container with tests
#         shell: bash -l {0}
#         run: |
#           docker pull sirf:devel
#           docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml run --rm -u jovyan --entrypoint /bin/bash sirf --login -c /devel/test.sh 1
      
#       - name: Build docker service-devel image
#         # Builds docker image from Docker file.
#         shell: bash -l {0}
#         run: |
#           docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml -f docker/docker-compose.srv.yml pull core
#           docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml -f docker/docker-compose.srv.yml build sirf

#       - name: Run docker devel container with tests
#         shell: bash -l {0}
#         run: |
#           docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml docker/docker-compose.srv.yml run --rm -u jovyan --entrypoint /bin/bash sirf --login -c /devel/test.sh 1
          
#       - name: List images 2
#         shell: bash -l {0}
#         run: |
#           docker image list
    # TODO: publish to come later
    # TODO: use matrix for tag names, yml names, etc.
