name: Docker build test devek, service, service-devel

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install docker and pre-reqs
        shell: bash -l {0}
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install ca-certificates curl gnupg lsb-release -y
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
          sudo docker run hello-world
      
      - name: Build docker devel image
        # Builds docker image from Docker file.
        shell: bash -l {0}
        run: |
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml pull core
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml build sirf

      - name: Run docker devel container with tests
        shell: bash -l {0}
        run: |
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml run --rm -u jovyan --entrypoint /bin/bash sirf --login -c /devel/test.sh 1
      
      - name: Build docker service-devel image
        # Builds docker image from Docker file.
        shell: bash -l {0}
        run: |
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml -f docker/docker-compose.srv.yml pull core
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml -f docker/docker-compose.srv.yml build sirf

      - name: Run docker service-devel container with tests
        shell: bash -l {0}
        run: |
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.devel.yml -f docker/docker-compose.srv.yml run --rm -u jovyan --entrypoint /bin/bash sirf --login -c /devel/test.sh 1
          
      - name: List images 2
        shell: bash -l {0}
        run: |
          docker image list
    # TODO: publish to come later
    # TODO: use matrix for tag names, yml names, etc.
